// Generated by `php artisan dashflow:error-codes`. Do not edit: change a module's Contracts/ErrorCode.php.
// Every code is `{module}.{snake_case}` and starts with its owning module name.
export enum ErrorCode {
    AccessContextMissing = 'access.context_missing',
    AccessInvitationsNotConfigured = 'access.invitations_not_configured',
    AccessLastUsersManageHolder = 'access.last_users_manage_holder',
    AccessNotAuthorized = 'access.not_authorized',
    AccessPermissionNotHeld = 'access.permission_not_held',
    AccessRevisionConflict = 'access.revision_conflict',
    AccessSelfChangeForbidden = 'access.self_change_forbidden',
    AccessWorkspaceForbidden = 'access.workspace_forbidden',
    ConnectorRevisionConflict = 'connector.revision_conflict',
    IdentityInvitationDeliveryFailed = 'identity.invitation_delivery_failed',
    IdentityInvitationInvalid = 'identity.invitation_invalid',
    PlatformCsrfTokenMismatch = 'platform.csrf_token_mismatch',
    PlatformForbidden = 'platform.forbidden',
    PlatformHttpError = 'platform.http_error',
    PlatformMethodNotAllowed = 'platform.method_not_allowed',
    PlatformNotFound = 'platform.not_found',
    PlatformServerError = 'platform.server_error',
    PlatformTooManyRequests = 'platform.too_many_requests',
    PlatformUnauthenticated = 'platform.unauthenticated',
    PlatformValidationFailed = 'platform.validation_failed',
}
