<?php

namespace App\Support\ErrorCodes;

use BackedEnum;
use InvalidArgumentException;

/**
 * Builds `resources/js/types/error-codes.ts` from the modules' `Contracts/ErrorCode.php` enums.
 * Every code is `{module}.{snake_case}` and starts with the name of the module that owns the enum.
 */
final class ErrorCodeGenerator
{
    public const OUTPUT = 'resources/js/types/error-codes.ts';

    /**
     * The ErrorCode enums under `$appPath`: the kernel's and every module's Contracts.
     *
     * @return list<class-string<BackedEnum>>
     */
    public static function discover(string $appPath): array
    {
        $files = array_merge(
            glob($appPath.'/Platform/Contracts/ErrorCode.php') ?: [],
            glob($appPath.'/Modules/*/Contracts/ErrorCode.php') ?: [],
        );
        sort($files);

        $classes = [];
        foreach ($files as $file) {
            $relative = substr($file, strlen(rtrim($appPath, '/')) + 1, -4);
            $classes[] = 'App\\'.str_replace('/', '\\', $relative);
        }

        /** @var list<class-string<BackedEnum>> $classes */
        return $classes;
    }

    /**
     * @param  array<string, class-string<BackedEnum>>|list<class-string<BackedEnum>>  $enums  owner => enum; a list derives the owner from the namespace
     * @return array<string, string> member name => code, sorted by code
     */
    public function codes(array $enums): array
    {
        $codes = [];

        foreach ($enums as $owner => $enum) {
            $owner = is_string($owner) ? $owner : self::owner($enum);

            foreach ($enum::cases() as $case) {
                $code = (string) $case->value;

                if (preg_match('/\A'.preg_quote($owner, '/').'\.[a-z][a-z0-9]*(?:_[a-z0-9]+)*\z/', $code) !== 1) {
                    throw new InvalidArgumentException("Error code {$code} in {$enum} must be {$owner}.{snake_case}: it must start with its owning module name.");
                }

                $member = str_replace(' ', '', ucwords(str_replace(['.', '_'], ' ', $code)));

                if (isset($codes[$code]) || in_array($member, $codes, true)) {
                    throw new InvalidArgumentException("Duplicate error code {$code}.");
                }

                $codes[$code] = $member;
            }
        }

        ksort($codes);

        return array_flip($codes);
    }

    /**
     * @param  array<string, class-string<BackedEnum>>|list<class-string<BackedEnum>>  $enums
     */
    public function render(array $enums): string
    {
        $lines = [
            '// Generated by `php artisan dashflow:error-codes`. Do not edit: change a module\'s Contracts/ErrorCode.php.',
            '// Every code is `{module}.{snake_case}` and starts with its owning module name.',
            'export enum ErrorCode {',
        ];

        foreach ($this->codes($enums) as $member => $code) {
            $lines[] = "    {$member} = '{$code}',";
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /** `App\Platform\Contracts\ErrorCode` is owned by `platform`, `App\Modules\Access\Contracts\ErrorCode` by `access`. */
    private static function owner(string $enum): string
    {
        if (preg_match('/^App\\\\Modules\\\\(\w+)\\\\Contracts\\\\ErrorCode$/', $enum, $m) === 1) {
            return strtolower($m[1]);
        }

        if ($enum === 'App\\Platform\\Contracts\\ErrorCode') {
            return 'platform';
        }

        throw new InvalidArgumentException("{$enum} is not a module's Contracts\\ErrorCode.");
    }
}
